version: "3.9"
services:
  backend:
    build:
      context: ./code-task-backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./code-task-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
